pool: OSX
  
stages:
- stage: Build 
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: Maven@3
      inputs:
       mavenPomFile: 'pom.xml'
        #mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'

  - job: sonar
    workspace:
      clean: all
    displayName:  Code Review
    steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'tarea-devsecops'
          organization: 'descudel'
          projectKey: 'descudel_pet-clinic'
          projectName: 'pet-clinic'
        displayName: 'Preparing Sonarqube Environment'
    
      - task: Gradle@3
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: "sonarqube"
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: true
          #sqGradlePluginVersionChoice: 'specify'
          sqMavenPluginVersionChoice: 'latest'
          #sonarQubeGradlePluginVersion: '3.3'
        displayName: 'Analyze current Branch'
    
  
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'
        displayName: 'Publish Analysis Results'
    
  #- task: sonarcloud-buildbreaker@2
  #  inputs:
  #    SonarCloud: 'Sonarcloud'
  #    organization: 'devsecops-usach'
